feat: add an error code for when a FunctionDecl was not compiled
functionless/functionless pull request #190
Opened 2022-06-02 23:01 UTC by brendo-m

Adding an error code for when we see a regular function that wasn't compiled by Functionless at synth time.

This is the first synth phase error so there is lots we can improve. Putting this for early feedback.

Example of the the error during synth

```
yarn synth
yarn run v1.22.18
$ cdk synth
/Users/brendan/workspace/binary/functionless/src/declaration.ts:101
    throw new SynthError(
          ^
SynthError: Expected input function to AppsyncResolver to be compiled by Functionless. Make sure you have the Functionless compiler plugin configured correctly.
    at validateFunctionDecl (/Users/brendan/workspace/binary/functionless/src/declaration.ts:101:11)
    at new AppsyncResolver (/Users/brendan/workspace/binary/functionless/src/appsync.ts:126:37)
    at Object.<anonymous> (/Users/brendan/workspace/binary/functionless/test-app/src/message-board.ts:62:25)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/Users/brendan/workspace/binary/functionless/test-app/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/brendan/workspace/binary/functionless/test-app/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: {
    code: 101,
    messageText: 'Function not compiled by Functionless plugin'
  }
}
```

2022-06-03 01:08 UTC, sam-goodwin requested changes

2022-06-03 01:12 UTC, brendo-m commented on src/error-code.ts
> +   * Ensure you follow the instructions at https://functionless.org/docs/getting-started.
this is a case where there isn't really anything we can provide as an example unless we include how to include the package.json and tsconfig setup

2022-06-03 07:02 UTC, sam-goodwin commented on src/error-code.ts
> +   * Ensure you follow the instructions at https://functionless.org/docs/getting-started.
Ohhhh I think I understand now, my bad. What you're saying is that the transformer is not properly configured.

2022-06-03 07:03 UTC, sam-goodwin approved these changes

2022-06-03 07:03 UTC, sam-goodwin commented on website/docs/error-codes.md
> +```
Why are these included in this change? Merging issue?

2022-06-04 03:50 UTC, thantos approved these changes

2022-06-05 21:25 UTC, merged