feat: add GetAccessorDecl, SetAccessorDecl and TaggedTemplateExpr, updated ObjectLiteralExpr to allow getters, setters and methods
functionless/functionless pull request #368
Opened 2022-07-28 20:56 UTC by sam-goodwin

Adds new AST nodes:
* GetAccessorDecl
* SetAccessorDecl
* TaggedTemplateExpr

Allows GetAccessorDecl, SetAccessorDecl and MethodDecl in ObjectLiteralExpr

2022-07-28 23:07 UTC, thantos requested changes

2022-07-28 23:08 UTC, sam-goodwin commented on src/aws.ts
> +        if (functionName.expr.kind !== "ReferenceExpr") {
oops, i saw that and thought to change it. then got distracted by something else lol

2022-07-28 23:12 UTC, sam-goodwin commented on src/declaration.ts
> +  }
Oops, good catch.

2022-07-28 23:20 UTC, sam-goodwin commented on src/api.ts
>              )}#if($foreach.hasNext),#end#end`;
typo - it can't be `undefined`.

2022-07-29 03:19 UTC, thantos commented
I cannot leave comments on lines that didn't change... :(

Missing `enusure` for OmitElm in visit.

2022-07-29 03:24 UTC, thantos commented
Errr, actually, where you going to update ArrayBinding to use OmittedExpr?

`export type ArrayBindingElement = BindingElement | OmittedExpression;`

2022-07-29 03:25 UTC, thantos approved these changes
Looks good, just the question of adding Omit for `ArrayBinding`. If not, ship it.

2022-07-29 03:26 UTC, thantos commented
Also looks like BindingElm name is ending up undefined now? (failed tests)

2022-07-29 08:17 UTC, merged